=== devefx/mirror-dev/mirror-test/src/main/resources/mirror-1.0.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
	targetNamespace="http://www.devefx.org/schema/mirror"
	xmlns="http://www.devefx.org/schema/mirror"
	elementFormDefault="qualified">
	
	<xsd:complexType name="identifiedType" abstract="true">
		<xsd:annotation>
			<xsd:documentation><![CDATA[
	The unique identifier for a bean. The scope of the identifier
	is the enclosing bean factory.
			]]></xsd:documentation>
		</xsd:annotation>
		<xsd:attribute name="id" type="xsd:string">
			<xsd:annotation>
				<xsd:documentation><![CDATA[
	The unique identifier for a bean. A bean id may not be used more than once
	within the same <beans> element.
				]]></xsd:documentation>
			</xsd:annotation>
		</xsd:attribute>
	</xsd:complexType>
	
	<xsd:element name="mirror">
		<xsd:annotation>
			<xsd:documentation><![CDATA[
	Container for <bean> and other elements, typically the root element in the document.
	Allows the definition of default values for all nested bean definitions. May itself
	be nested for the purpose of defining a subset of beans with certain default values or
	to be registered only when certain profile(s) are active. Any such nested <beans> element
	must be declared as the last element in the document.
			]]></xsd:documentation>
		</xsd:annotation>
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element ref="description" minOccurs="0"/>
				<xsd:choice minOccurs="1" maxOccurs="unbounded">
					<xsd:element ref="bean"/>
					<xsd:element ref="property-file"/>
					<xsd:any namespace="##other" processContents="strict" minOccurs="0" maxOccurs="unbounded"/>
				</xsd:choice>
				<xsd:element ref="setting" maxOccurs="1" minOccurs="1"/>
			</xsd:sequence>
			<xsd:anyAttribute namespace="##other" processContents="lax"/>
		</xsd:complexType>
	</xsd:element>
	
	<xsd:element name="description">
		<xsd:annotation>
			<xsd:documentation><![CDATA[
	Contains informative text describing the purpose of the enclosing element.
	Used primarily for user documentation of XML bean definition documents.
			]]></xsd:documentation>
		</xsd:annotation>
		<xsd:complexType mixed="true">
			<xsd:choice minOccurs="0" maxOccurs="unbounded"/>
		</xsd:complexType>
	</xsd:element>
	
	<xsd:group name="beanElements">
		<xsd:sequence>
			<xsd:choice minOccurs="0" maxOccurs="unbounded">
				<xsd:element ref="constructor-arg"/>
				<xsd:element ref="property"/>
				<xsd:any namespace="##other" processContents="strict" minOccurs="0" maxOccurs="unbounded"/>
			</xsd:choice>
		</xsd:sequence>
	</xsd:group>
	
	<xsd:attributeGroup name="beanAttributes">
		<xsd:attribute name="class" type="xsd:string">
			<xsd:annotation>
				<xsd:documentation source="java:java.lang.Class"><![CDATA[
	The fully qualified name of the bean's class, except if it serves only
	as a parent definition for child bean definitions.
				]]></xsd:documentation>
			</xsd:annotation>
		</xsd:attribute>
		<xsd:attribute name="init-method" type="xsd:string">
			<xsd:annotation>
				<xsd:documentation><![CDATA[
	The name of the custom initialization method to invoke after setting
	bean properties. The method must have no arguments, but may throw any
	exception.

	This is an alternative to implementing Spring's InitializingBean
	interface or marking a method with the PostConstruct annotation.
				]]></xsd:documentation>
			</xsd:annotation>
		</xsd:attribute>
	</xsd:attributeGroup>
	
	<xsd:element name="bean">
		<xsd:annotation>
			<xsd:documentation><![CDATA[
	Defines a single (usually named) bean.

	A bean definition may contain nested tags for constructor arguments,
	property values, lookup methods, and replaced methods. Mixing constructor
	injection and setter injection on the same bean is explicitly supported.
			]]></xsd:documentation>
		</xsd:annotation>
		<xsd:complexType>
			<xsd:complexContent>
				<xsd:extension base="identifiedType">
					<xsd:group ref="beanElements"/>
					<xsd:attributeGroup ref="beanAttributes"/>
				</xsd:extension>
			</xsd:complexContent>
		</xsd:complexType>
	</xsd:element>
	
	<xsd:element name="constructor-arg">
		<xsd:complexType>
			<xsd:sequence minOccurs="0" maxOccurs="1">
				<xsd:element ref="description" minOccurs="0"/>
				<xsd:choice>
					<xsd:element ref="list"/>
					<xsd:element ref="map"/>
					<xsd:any namespace="##other" processContents="strict"/>
				</xsd:choice>
			</xsd:sequence>
			<xsd:attribute name="index" type="xsd:string"/>
			<xsd:attribute name="ref" type="xsd:string"/>
			<xsd:attribute name="value" type="xsd:string"/>
		</xsd:complexType>
	</xsd:element>
	
	<xsd:element name="property" type="propertyType"/>
		
	<xsd:complexType name="propertyType">
		<xsd:sequence>
			<xsd:element ref="description" minOccurs="0"/>
			<xsd:choice minOccurs="0" maxOccurs="1">
				<xsd:element ref="list"/>
				<xsd:element ref="map"/>
				<xsd:any namespace="##other" processContents="strict"/>
			</xsd:choice>
		</xsd:sequence>
		<xsd:attribute name="name" type="xsd:string" use="required"/>
		<xsd:attribute name="ref" type="xsd:string"/>
		<xsd:attribute name="value" type="xsd:string"/>
	</xsd:complexType>
	
	<xsd:element name="list">
		<xsd:complexType>
			<xsd:group ref="collectionElements"/>
		</xsd:complexType>
	</xsd:element>
	
	<xsd:group name="collectionElements">
		<xsd:sequence>
			<xsd:element ref="description" minOccurs="0"/>
			<xsd:choice minOccurs="0" maxOccurs="unbounded">
				<xsd:element ref="value"/>
				<xsd:element ref="ref"/>
			</xsd:choice>
		</xsd:sequence>
	</xsd:group>
	
	<xsd:element name="value">
		<xsd:complexType mixed="true">
			<xsd:choice minOccurs="0" maxOccurs="unbounded"/>
		</xsd:complexType>
	</xsd:element>
	
	<xsd:element name="ref">
		<xsd:complexType>
			<xsd:complexContent>
				<xsd:restriction base="xsd:anyType">
					<xsd:attribute name="bean" type="xsd:string" use="required"/>
				</xsd:restriction>
			</xsd:complexContent>
		</xsd:complexType>
	</xsd:element>
	
	<xsd:element name="map">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element ref="description" minOccurs="0"/>
				<xsd:choice minOccurs="0" maxOccurs="unbounded">
					<xsd:element ref="entry"/>
				</xsd:choice>
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>
	
	<xsd:element name="entry">
		<xsd:complexType>
			<xsd:attribute name="key" type="xsd:string"/>
			<xsd:attribute name="key-ref" type="xsd:string"/>
			<xsd:attribute name="value" type="xsd:string"/>
			<xsd:attribute name="value-ref" type="xsd:string"/>
		</xsd:complexType>
	</xsd:element>
	
	<xsd:element name="property-file">
		<xsd:complexType>
			<xsd:attribute name="resource"/>
			<xsd:attribute name="url"/>
		</xsd:complexType>
	</xsd:element>
	
	<xsd:element name="setting">
		<xsd:complexType>
			<xsd:attribute name="dataSource" use="required">
				<xsd:annotation>
					<xsd:documentation source="java:javax.sql.DataSource"/>
				</xsd:annotation>
			</xsd:attribute>
			<xsd:attribute name="cache"/>
		</xsd:complexType>
	</xsd:element>
</xsd:schema>

=== devefx/mirror-dev/mirror-test/src/main/resources/mirror.xml
<?xml version="1.0" encoding="UTF-8"?>
<mirror xmlns="http://www.devefx.org/schema/mirror"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.devefx.org/schema/mirror mirror-1.0.xsd">
	
	<!-- 引入属性文件 -->
	<property-file resource="setting.properties"/>
	
	<bean id="testBean" class="test.TestBean">
		<constructor-arg ref="dataSource"/>
		<constructor-arg>
			<list>
				<value>a</value>
				<value>b</value>
			</list>
		</constructor-arg>
		<constructor-arg>
			<map>
				<entry key="a" value="1"/>
				<entry key="b" value-ref="dataSource"/>
			</map>
		</constructor-arg>
		<constructor-arg value="名称"/>
		
		<property name="dataSource" ref="dataSource" />
	</bean>
	
	<!-- 配置数据源 -->
	<bean id="dataSource" class="com.alibaba.druid.pool.DruidDataSource" init-method="init">
		<!-- 连接信息 -->
		<property name="url" value="${jdbc.url}"/>
		<property name="username" value="${jdbc.user}"/>
		<property name="password" value="${jdbc.password}"/>
		<!-- 初始化设置 -->
		<property name="initialSize" value="1" />
		<property name="maxActive" value="20" />
		<property name="minIdle" value="1" />
		<property name="maxWait" value="60000" />
		<!-- 验证设置 -->
		<property name="validationQuery" value="${jdbc.validationQuery}"/>
		<property name="testOnBorrow" value="true"/>
		<property name="testOnReturn" value="true" />
		<property name="testWhileIdle" value="true" />
	</bean>
	
	<!-- <dataSource type="sqlmap.engine.datasource.MultiDataSource">
		<property name="readDataSource">
			<list>
				<ref bean=""/>
			</list>
		</property>
		<property name="writeDataSource">
			<list>
				
			</list>
		</property>
		<property name=""/>
	</dataSource> -->
	
	<bean class="test.TestBean">
		<constructor-arg ref="dataSource"/>
		<constructor-arg>
			<list>
				<value>1</value>
				<value>2</value>
			</list>
		</constructor-arg>
		<constructor-arg>
			<map>
				<entry key="a" value="1"/>
				<entry key="b" value-ref="dataSource"/>
				<entry key-ref="dataSource" value="这是数据源"/>
			</map>
		</constructor-arg>
		<constructor-arg value="文章"/>
		<property name="dataSource" ref="dataSource" />
	</bean>
	
	<setting dataSource="dataSource1"/>
	
</mirror>
